### ISSUE TITLE
Message d'erreur toutes les nuits..

### ISSUE THREAD

**Issue by PhilippeRigaux** [BisonJeedom/documentations#4]
Suite à cette "amélioration" je reçois un message d'erreur toutes les nuits.. En effet, mon système a de grosses batteries et du coup, il continue a produire toute la nuit, donc, je dépasse les seuil d'alerte toutes les nuits..

Y. a t il un paramètre à changer pour éviter ces erreurs?

Merci

05/10/2024
Améliorations :
Ajout d'un contrôle à 3h05 pour vérifier que la valeur de production n'est pas trop élevée (> 500 W) car pouvant montrer un problème

**Comment by BisonJeedom** [comment]
Bonsoir,

Possible de passer sur https://community.jeedom.com/ pour échanger et fournir plus de détails ?

Je ne comprends pas trop comment la fourniture d'énergie par une batterie vient alimenter la commande de production.

**Comment by PhilippeRigaux** [comment]
Bonsoir,

OK, c’est fait:

https://community.jeedom.com/t/erreur-attention-prod-value/132672/25

J’ai ouvert une issue sur le GitHub car j’ai ce message toutes les nuits…

Mes inverters Solax G4 ne comptent la production que quand on consomme l’énergie, pas lorsqu’ils chargent leur batteries…

Donc pendant toute la nuit, la production continue à augmenter…

L’ancien fonctionnement était parfait pour eux…



Cordialement



Philippe

**Comment by BisonJeedom** [comment]
Bonsoir,

Si tu n'as pas vu sur Community, j'ai poussé une version bêta ce matin. Peux-tu valider ?

**Comment by BisonJeedom** [comment]
Possibilité de masquer cette alerte dans la dernière version stable
